# Reading Preprocessed Data

In [1]:
import pandas as pd

In [94]:
df = pd.read_csv('training.csv')
label = pd.read_csv('label.csv')

In [3]:
df.head()

Unnamed: 0                                          0  \
0           0                 [0.42745072959635044, 1.0]   
1           1   [0.3021271072523665, 0.8949215382418432]   
2           2  [0.40969140138574034, 0.9672668768967665]   
3           3   [0.3172687061175035, 0.5796835084861404]   
4           4   [0.45023795040612585, 0.803920618642722]   

                                           1  \
0                  [0.4431369623068533, 1.0]   
1   [0.3446808182526158, 0.8949215382418432]   
2  [0.41850261289738927, 0.9672668768967665]   
3  [0.32530142400937295, 0.5796835084861404]   
4   [0.45971589079328723, 0.803920618642722]   

                                           2  \
0                 [0.45882319501735613, 1.0]   
1   [0.3702120167680615, 0.8949215382418432]   
2   [0.4361237055248678, 0.9508990796666634]   
3  [0.34136564694124827, 0.5796835084861404]   
4   [0.46919526246108706, 0.803920618642722]   

                                           3  \
0  [0.48235313623987564, 0.9846379016807152]   
1  [0.39574450038938713, 0.8949215382418432]   
2  [0.48898698340730334, 0.9345337537935329]   
3   [0.3574298698731236, 0.5796835084861404]   
4    [0.4976305149032096, 0.803920618642722]   

                                           4  \
0   [0.5058818931488647, 0.9846379016807152]   
1  [0.43829821138963637, 0.9299476921612289]   
2   [0.5066080760347819, 0.9345337537935329]   
3  [0.38152681069686833, 0.5796835084861404]   
4    [0.5165878269581707, 0.803920618642722]   

                                          5  \
0  [0.5215681258593675, 0.9846379016807152]   
1  [0.4553194387685601, 0.9299476921612289]   
2  [0.5242291686622604, 0.9181659565634298]   
3  [0.4136552565606189, 0.5971979076864492]   
4  [0.5260671986259705, 0.8217472404131104]   

                                          6  \
0   [0.545098067081887, 0.9846379016807152]   
1  [0.4553194387685601, 0.8949215382418432]   
2  [0.5242291686622604, 0.8526997103569628]   
3  [0.4297194794924942, 0.5971979076864492]   
4  [0.5545024510680931, 0.8395738621834987]   

                                           7  \
0   [0.5607842997923899, 0.9846379016807152]   
1   [0.4553194387685601, 0.8598953843224575]   
2   [0.5154179571506114, 0.7708681382773653]   
3  [0.45381520746437554, 0.6147096624055259]   
4   [0.5639818227358929, 0.8573977923304884]   

                                           8  ...  168  169  170  171  172  \
0    [0.568626823990876, 0.9846379016807152]  ...  NaN  NaN  NaN  NaN  NaN   
1   [0.4553194387685601, 0.7548142780830686]  ...  NaN  NaN  NaN  NaN  NaN   
2   [0.5154179571506114, 0.6890340948407951]  ...  NaN  NaN  NaN  NaN  NaN   
3  [0.46987943039625085, 0.6147096624055259]  ...  NaN  NaN  NaN  NaN  NaN   
4   [0.5734597631230544, 0.8573977923304884]  ...  NaN  NaN  NaN  NaN  NaN   

   173  174  175  176  177  
0  NaN  NaN  NaN  NaN  NaN  
1  NaN  NaN  NaN  NaN  NaN  
2  NaN  NaN  NaN  NaN  NaN  
3  NaN  NaN  NaN  NaN  NaN  
4  NaN  NaN  NaN  NaN  NaN  

[5 rows x 179 columns]

# PyTorch Implementation

In [2]:
# https://gist.github.com/dolaameng/8918fefc05d0589f66279eab763d1e13

import torch
import torch.nn as nn
from torch.autograd import Variable

In [5]:
batch_size = 3
max_length = 3
hidden_size = 2
n_layers = 1

# container
batch_in = torch.zeros((batch_size, max_length, 1))

#data
vec_1 = torch.FloatTensor([[9, 2, 3]])
vec_2 = torch.FloatTensor([[1, 2, 0]])
vec_3 = torch.FloatTensor([[1, 0, 0]])

batch_in[0] = vec_1.reshape(-1, 1)
batch_in[1] = vec_2.reshape(-1, 1)
batch_in[2] = vec_3.reshape(-1, 1)

batch_in = Variable(batch_in)

seq_lengths = [3,2,1]

pack = torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True)

# print(batch_in.size()) # >>> torch.Size([3, 3, 1])

rnn = nn.RNN(1, hidden_size, n_layers, batch_first=True) 
h0 = Variable(torch.randn(n_layers, batch_size, hidden_size))

out, _ = rnn(pack, h0)

unpacked, unpacked_len = torch.nn.utils.rnn.pad_packed_sequence(out)

# print(unpacked.size()) # >>> torch.Size([3, 3, 2])
# print(unpacked_len) # >>> [3, 2, 1]
print(unpacked[2, ...]) 

tensor([[-0.6548, -0.8826],
        [ 0.0000,  0.0000],
        [ 0.0000,  0.0000]], grad_fn=<SelectBackward0>)


In [23]:
pack

PackedSequence(data=tensor([[1.],
        [1.],
        [1.],
        [2.],
        [2.],
        [3.]]), batch_sizes=tensor([3, 2, 1]), sorted_indices=None, unsorted_indices=None)

In [20]:
h0

tensor([[[ 1.0169, -1.4825],
         [ 0.9579, -0.7064],
         [ 1.0794, -0.1054]]])

In [131]:
out_map = ['chA', 'a', 'ai', 'bA', 'tA']

In [132]:
label['label_index'] = label[['0']].applymap(lambda x: out_map.index(x))

In [114]:
labels = label['label_index'].values

In [135]:
from sklearn.preprocessing import OneHotEncoder

In [137]:
onehot_data = OneHotEncoder(sparse=False)
onehot_data = onehot_data.fit_transform(labels.reshape(-1, 1))

In [139]:
onehot_data

(345, 5)

In [6]:
import ast
import numpy as np

In [7]:
max_seq_len = 200

In [84]:
samples = df.values[:,1:]

In [85]:
inps = [torch.tensor([ast.literal_eval(i) for i in sample_i if type(i)==str]) for sample_i in samples]

In [115]:
inp_len_tuple = [(val, val.shape[0], labels[i]) for i,val in enumerate(inps)]

In [116]:
sorted_inp_len_tuple = sorted(inp_len_tuple, key=lambda x: x[1], reverse=True)
inputs = [i[0] for i in sorted_inp_len_tuple]
seq_lens = [i[1] for i in sorted_inp_len_tuple]
sorted_labels = [i[2] for i in sorted_inp_len_tuple]

In [88]:
# inps = [[k for k in i] + ([[0,0]] * (max_seq_len - len(i))) for i in inps]

In [91]:
padded_seq_batch = torch.nn.utils.rnn.pad_sequence(inputs, batch_first=True)

In [90]:
# packed_seq_batch = torch.nn.utils.rnn.pack_padded_sequence(padded_seq_batch, lengths=seq_lens, batch_first=True)

In [150]:
m = nn.Softmax(dim=1)
i = torch.randn(2, 3)
output = m(i)

In [152]:
i

tensor([[-1.3853,  1.0028,  1.0099],
        [ 0.3264,  1.1759,  0.0283]])

In [151]:
output

tensor([[0.0437, 0.4764, 0.4799],
        [0.2451, 0.5731, 0.1819]])

In [316]:
class RNN(nn.Module):
    def __init__(self, input_dim=2, hidden_dim=178, output_dim=5):
        super().__init__()
        self.rnn = nn.RNN(input_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, padded_seq_batch,seq_lens):
        #x [sent length , batch size]
        packed_seq_batch = torch.nn.utils.rnn.pack_padded_sequence(padded_seq_batch, lengths=seq_lens, batch_first=True)
        # packed_embedded = nn.utils.rnn.pack_padded_sequence(embedded, text_lengths)
        packed_output, hidden = self.rnn(packed_seq_batch)#[sentence length,batch size, hidden dim],[1,batch size,hidden dim]
        # output, output_lengths = nn.utils.rnn.pad_packed_sequence(packed_output)
        return self.fc(hidden.squeeze(0))

In [317]:
model = RNN()
model

RNN(
  (rnn): RNN(2, 178)
  (fc): Linear(in_features=178, out_features=5, bias=True)
)

In [318]:
import torch.optim as optim

In [319]:
optimizer = optim.SGD(model.parameters(), lr=1e-3)

In [320]:
criterion = nn.CrossEntropyLoss()

In [321]:
device = 'cpu'

model = model.to(device)
criterion = criterion.to(device)

In [322]:
iterator = [{'padded_seq_batch': padded_seq_batch, 'seq_lens': seq_lens, 'label': torch.Tensor(onehot_data)}]

In [323]:
iterator[0]['label'].size()

torch.Size([345, 5])

In [324]:
def accuracy(preds, y):
    rounded_preds = torch.round(torch.sigmoid(preds))
    correct = (rounded_preds == y).float()
    acc = correct.sum()/len(correct)
    return acc

def train(model, iterator, optimizer, criterion):
    epoch_loss = 0
    epoch_acc = 0
    model.train()
    for batch in iterator:
        optimizer.zero_grad()
        predictions = model(batch["padded_seq_batch"], batch["seq_lens"]).squeeze(1)
        loss = criterion(predictions, batch["label"])
        acc = one_hot_accuracy(predictions, batch["label"])
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

def evaluate(model, iterator, criterion):
    epoch_loss = 0
    epoch_acc = 0
    model.eval()
    with torch.no_grad():
        for batch in iterator:
            predictions = model(batch["padded_seq_batch"],batch["seq_lens"]).squeeze(1)
            loss = criterion(predictions, batch["label"])
            acc = one_hot_accuracy(predictions, batch["label"])

            epoch_loss += loss.item()
            epoch_acc += acc.item()
        
    return epoch_loss / len(iterator), epoch_acc / len(iterator)

In [325]:
def softmax(e_l1):
    e = np.exp(e_l1 - np.max(e_l1))
    S = np.sum(e,axis=1)
    P = e/np.expand_dims(S, 1)
    return P

In [326]:
def one_hot_accuracy(predictions, onehot_data):
    pred_list = [[float(p) for p in pred] for pred in predictions]
    total_sum = np.sum(softmax(pred_list) * np.array(onehot_data), axis=1)
    accuracy = sum(total_sum)/len(total_sum)
    return accuracy

In [327]:
for epoch in range(10):
    train_loss, train_acc = train(model, iterator, optimizer, criterion)
    valid_loss, valid_acc = evaluate(model, iterator, criterion)    
    print(f'| Epoch: {epoch+1:02} | Train Loss: {train_loss:.3f} | Train Acc: {train_acc*100:.2f}% | Val. Loss: {valid_loss:.3f} | Val. Acc: {valid_acc*100:.2f}% |')

| Epoch: 01 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 02 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 03 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 04 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 05 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 06 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 07 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 08 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 09 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |
| Epoch: 10 | Train Loss: 1.613 | Train Acc: 20.01% | Val. Loss: 1.613 | Val. Acc: 20.01% |


In [63]:
lstm = nn.LSTM(input_size=2, hidden_size=5, batch_first=True)
output, (hn, cn) = lstm(packed_seq_batch.float())

In [26]:
padded_output, output_lens = torch.nn.utils.rnn.pad_packed_sequence(output, batch_first=True, total_length=178)

In [29]:
padded_seq_batch.shape

torch.Size([345, 178, 2])

In [28]:
padded_output.shape

torch.Size([345, 178, 3])

In [ ]:
class RNN(nn.Module):
    def __init__(self, input_dim, embedding_dim, hidden_dim, output_dim):
        super().__init__()
        
        self.embedding = nn.Embedding(input_dim, embedding_dim)
        self.rnn = nn.RNN(embedding_dim, hidden_dim)
        self.fc = nn.Linear(hidden_dim, output_dim)
        
    def forward(self, x):

        #x = [sent len, batch size]
        
        embedded = self.embedding(x)
        
        #embedded = [sent len, batch size, emb dim]
        
        output, hidden = self.rnn(embedded)
        
        #output = [sent len, batch size, hid dim]
        #hidden = [1, batch size, hid dim]
        
        assert torch.equal(output[-1,:,:], hidden.squeeze(0))
        
        out = self.fc(hidden)
        return out

# Keras Implementation

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [140]:
# raw_inputs = [
#     [711.0, 632.9, 71],
#     [73, 8, 3215, 55, 927],
#     [83, 91, 1, 645, 1253, 927],
# ]

# By default, this will pad using 0s; it is configurable via the
# "value" parameter.
# Note that you could "pre" padding (at the beginning) or
# "post" padding (at the end).
# We recommend using "post" padding when working with RNN layers
# (in order to be able to use the
# CuDNN implementation of the layers).
padded_inputs = tf.keras.preprocessing.sequence.pad_sequences(
    inps, padding="post", dtype='float32'
)
print(padded_inputs)

[[[0.42745072 1.        ]
  [0.44313696 1.        ]
  [0.4588232  1.        ]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.3021271  0.89492154]
  [0.34468082 0.89492154]
  [0.37021202 0.89492154]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.4096914  0.96726686]
  [0.4185026  0.96726686]
  [0.4361237  0.95089906]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 ...

 [[0.560976   0.61965007]
  [0.57073134 0.61965007]
  [0.58048815 0.61965007]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.65898633 0.6557666 ]
  [0.66820216 0.6385536 ]
  [0.6774194  0.6385536 ]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]

 [[0.5637854  0.6557666 ]
  [0.5802462  0.6557666 ]
  [0.58847725 0.6557666 ]
  ...
  [0.         0.        ]
  [0.         0.        ]
  [0.         0.        ]]]


In [143]:
class MyLayer(layers.Layer):
    def __init__(self, **kwargs):
        super(MyLayer, self).__init__(**kwargs)
        self.embedding = layers.Embedding(input_dim=5000, output_dim=16, mask_zero=True)
        self.lstm = layers.LSTM(32)

    def call(self, inputs):
        x = self.embedding(inputs)
        # Note that you could also prepare a `mask` tensor manually.
        # It only needs to be a boolean tensor
        # with the right shape, i.e. (batch_size, timesteps).
        mask = self.embedding.compute_mask(inputs)
        output = self.lstm(x, mask=mask)  # The layer will ignore the masked values
        return output


layer = MyLayer()
x = np.random.random((32, 10)) * 100
x = x.astype("int32")
# layer(x)

In [146]:
hidden_neurons = 4
nb_classes = 3
embedding_size =10

X = np.zeros((128, hidden_neurons), dtype=np.float32)
y = np.zeros((128, nb_classes), dtype=np.int8)


model = Sequential()
model.add(Embedding(hidden_neurons, embedding_size))
model.add(SimpleRNN(hidden_neurons, return_sequences=False)) 
model.add(Dense(nb_classes))
model.add(Activation("softmax"))
model.compile(loss='categorical_crossentropy', optimizer='rmsprop')
model.fit(X, y, batch_size=1)

128/128 [==============================] - 1s 2ms/step - loss: 0.0000e+00


In [12]:
embedding = layers.Embedding(input_dim=len(padded_inputs), output_dim=5, mask_zero=True)

In [ ]:
masked_output = embedding(padded_inputs)

In [115]:
embedding = layers.Embedding(input_dim=5000, output_dim=5, mask_zero=True)
masked_output = embedding(padded_inputs)

print(masked_output._keras_mask)

masking_layer = layers.Masking()
# Simulate the embedding lookup by expanding the 2D input to 3D,
# with embedding dimension of 10.
unmasked_embedding = tf.cast(
    tf.tile(tf.expand_dims(padded_inputs, axis=-1), [1, 1, 10]), tf.float32
)

masked_embedding = masking_layer(unmasked_embedding)
print(masked_embedding._keras_mask)

tf.Tensor(
[[ True  True  True False False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]], shape=(3, 6), dtype=bool)
tf.Tensor(
[[ True  True  True False False False]
 [ True  True  True  True  True False]
 [ True  True  True  True  True  True]], shape=(3, 6), dtype=bool)


# Keras attempt 2

In [116]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import Embedding, LSTM, Dense, Dropout, SimpleRNN, Masking, Input, Activation
from tensorflow.keras.activations import softmax
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.models import Sequential, Model
import tensorflow.keras.utils as ku
import numpy as np

In [86]:
# coordinates = np.random.random([10000, 50, 3]).astype(np.float32)
# temps = np.random.rand(10000,50)

# # ----- Define RNN model -----
# rnn_model = tf.keras.Sequential()
# rnn_model.add(tf.keras.layers.SimpleRNN(128))
# rnn_model.add(tf.keras.layers.Dense(50))

# # ----- Compile model -----
# rnn_model.compile(loss='mean_squared_error', optimizer=tf.keras.optimizers.Adam(1e-4))

# ----- Train model -----
# history = rnn_model.fit(x=coordinates, y=temps, batch_size=32,epochs=50)

In [25]:
coordinates.shape

(10000, 50, 3)

In [124]:
padded_inputs.shape

(345, 178, 2)

In [139]:
# https://stackoverflow.com/questions/64276284/how-to-build-a-one-to-many-rnn-in-tensorflow

model = Sequential()
model.add(SimpleRNN(200))
model.add(Dense(5, activation='softmax'))

In [132]:
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])

In [133]:
unique_val = out['0'].unique()
def _apply_index(x):
    return list(unique_val).index(x)

In [134]:
y = out['0'].apply(lambda x: _apply_index(x)).values

In [136]:
history = model.fit(x=padded_inputs, y=y, batch_size=32,epochs=5)

Epoch 1/5
11/11 [==============================] - 0s 38ms/step - loss: 5.2041 - accuracy: 0.1913
Epoch 2/5
11/11 [==============================] - 0s 34ms/step - loss: 5.2041 - accuracy: 0.2464
Epoch 3/5
11/11 [==============================] - 0s 34ms/step - loss: 5.2041 - accuracy: 0.2290
Epoch 4/5
11/11 [==============================] - 0s 33ms/step - loss: 5.2041 - accuracy: 0.2000
Epoch 5/5
11/11 [==============================] - 0s 34ms/step - loss: 5.2041 - accuracy: 0.1884


In [137]:
model.summary()

Model: "sequential_13"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_11 (SimpleRNN)    (None, 200)               40600     
_________________________________________________________________
dense_11 (Dense)             (None, 5)                 1005      
Total params: 41,605
Trainable params: 41,605
Non-trainable params: 0
_________________________________________________________________


In [138]:
model.predict(padded_inputs[:-5])

array([[0.1998206 , 0.19999546, 0.19960669, 0.20000932, 0.20056786],
       [0.19996426, 0.19967175, 0.19993274, 0.1999912 , 0.2004401 ],
       [0.19982499, 0.20018087, 0.19972503, 0.19983442, 0.2004346 ],
       ...,
       [0.20011291, 0.19995978, 0.19973402, 0.19986778, 0.20032555],
       [0.20048244, 0.20019385, 0.20017317, 0.20033269, 0.1988179 ],
       [0.1999656 , 0.19973756, 0.19994004, 0.19998191, 0.2003749 ]],
      dtype=float32)

In [120]:
padded

(345, 178, 2)

In [ ]:
pred_test = model.predict(padded_inputs[:-5])
true_test = model.predict(padded_input2[:-5])

In [ ]:
plt.plot(iteration_list,loss_list)
plt.xlabel("epoch")
plt.ylabel("error")
plt.title("Average error vs epoch.")
plt.show()

plt.plot(iteration_list,accuracy_list,color = "red")
plt.xlabel("epoch")
plt.ylabel("Accuracy")
plt.title("Accuracy vs epoch")
plt.show()

In [ ]:
pred1_test=np.array(pred_test)
pred1_test.shape
true1_test=np.array(true_test)
print(true1_test.shape)

In [1]:
from sklearn.metrics import confusion_matrix
cm_test=confusion_matrix(true1_test,pred1_test)
print(cm_test)

[[55, 13, 2, 2, 5],
 [3, 46, 5, 4, 1],
 [7, 4, 32, 27, 6],
 [3, 6, 26, 34, 2],
 [2, 3, 8, 3, 55]]