# Convolution

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd
import os
import cv2

In [2]:
import tensorflow as tf

### Reading data as image and resizing and test, train & validation separated

In [11]:
def read_data(path):
    
    train_path = path+"/train"
    test_path = path+"/test"
    validation_path = path+"/val"
    
    tr_data, test_data, val_data = [], [], []
    tr_out, test_out, val_out = [], [], []

    for i in os.listdir(train_path):

        try:
            for j in os.listdir(train_path+"/"+i):
                image = cv2.imread(train_path+"/"+i+"/"+j, cv2.IMREAD_GRAYSCALE)
                tr_data.append(cv2.resize(image, (224, 224)))
                tr_out.append(i)

            for j in os.listdir(test_path+"/"+i):
                image = cv2.imread(test_path+"/"+i+"/"+j, cv2.IMREAD_GRAYSCALE)
                test_data.append(cv2.resize(image, (224, 224)))
                test_out.append(i)

            for j in os.listdir(validation_path+"/"+i):
                image = cv2.imread(validation_path+"/"+i+"/"+j, cv2.IMREAD_GRAYSCALE)
                val_data.append(cv2.resize(image, (224, 224)))
                val_out.append(i)
        except:
            pass
                
                
    tr_data, test_data, val_data = np.array(tr_data), np.array(test_data), np.array(val_data)
    tr_out, test_out, val_out = np.array(tr_out), np.array(test_out), np.array(val_out)

    return tr_data, test_data, val_data, tr_out, test_out, val_out



In [12]:
path = "/Users/rajeshr/Desktop/Group_22"
tr_data, test_data, val_data, tr_out, test_out, val_out = read_data(path)

## Kaiming Initializatied Filter

In [167]:
def kaiming(n, size):
    mean, sd = 0, np.sqrt(2/n)
    weights = np.random.normal(mean, sd, size=size)
    return weights

In [283]:
np.random.seed(0)
n = 1
filtr = kaiming(n, (3, 3))
filtr

array([[ 2.49474675,  0.56590775,  1.38414453],
       [ 3.16910155,  2.64112584, -1.38207963],
       [ 1.34362793, -0.21405142, -0.1459735 ]])

## Convolutional Filter

In [278]:
def zero_padding(inpt, filtr):
    
    (m, n), (fm, fn) = inpt.shape, filtr.shape
        
    if fm%2 == 0:
        print("Filter size is not odd, creates issues in future")
    
    l = int((fm-1)/2)
    #print(l)
    
    temp = []
    for i in range(l):
        for j in range(m+2*l):
            temp.append(0)
            
    for i in inpt:
        
        for j in range(l):
            temp.append(0)
        
        for p in i:
            temp.append(p)
            
        for k in range(l):
            temp.append(0)
            
    for i in range(l):
        for j in range(m+2*l):
            temp.append(0)
    
    
    temp = np.array(temp, dtype=np.uint8)
    temp = temp.flatten()
    temp = temp.reshape(m+2*l, n+2*l)
    
    return temp

In [284]:
def convolution(inpt, filtr , stride, padding):
    
    if padding:
        inpt = zero_padding(inpt, Cfilter)
        
    print(inpt)
    feature_map = []
    
    
    
    
    return feature_map

convolution(tr_data[0], filtr, 1, True)

[[  0   0   0 ...   0   0   0]
 [  0   7  11 ...  19  19   0]
 [  0  13  11 ...  19  19   0]
 ...
 [  0  67  75 ... 142 136   0]
 [  0  68  72 ... 139 152   0]
 [  0   0   0 ...   0   0   0]]


[]